import type { ShoppingListItem } from "@/lib/shopping-list";

export type ShoppingPdfGroup = {
  heading: string;
  items: ShoppingListItem[];
};

export function groupShoppingItems(items: ShoppingListItem[]): ShoppingPdfGroup[] {
  const groups = new Map<string, ShoppingListItem[]>();

  for (const item of items) {
    const heading = item.dish?.trim() || "Extra items";
    groups.set(heading, [...(groups.get(heading) || []), item]);
  }

  return Array.from(groups, ([heading, groupItems]) => ({ heading, items: groupItems }));
}

export async function downloadShoppingListPdf(items: ShoppingListItem[]) {
  if (!items.length) return;

  const { jsPDF } = await import("jspdf");
  const document = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = document.internal.pageSize.getWidth();
  const pageHeight = document.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const bought = items.filter((item) => item.checked).length;
  const groups = groupShoppingItems(items);
  let y = 20;

  function addPageIfNeeded(height: number) {
    if (y + height <= pageHeight - 18) return;
    document.addPage();
    y = 20;
  }

  document.setFillColor(249, 115, 22);
  document.roundedRect(margin, y, contentWidth, 24, 4, 4, "F");
  document.setTextColor(255, 255, 255);
  document.setFont("helvetica", "bold");
  document.setFontSize(20);
  document.text("AI Chef Shopping Bill", margin + 6, y + 10);
  document.setFont("helvetica", "normal");
  document.setFontSize(9);
  document.text(new Date().toLocaleDateString(), margin + 6, y + 17);
  y += 33;

  document.setTextColor(34, 34, 34);
  document.setFontSize(10);
  document.text(
    `${items.length} total items  |  ${bought} picked  |  ${items.length - bought} remaining`,
    margin,
    y
  );
  y += 9;

  for (const group of groups) {
    addPageIfNeeded(20);
    document.setFillColor(255, 244, 236);
    document.roundedRect(margin, y, contentWidth, 10, 2, 2, "F");
    document.setTextColor(234, 88, 12);
    document.setFont("helvetica", "bold");
    document.setFontSize(11);
    const heading = group.heading === "Extra items" ? group.heading : `Recipe: ${group.heading}`;
    document.text(heading, margin + 4, y + 6.5);
    document.setFontSize(8);
    document.text(
      `${group.items.length} item${group.items.length === 1 ? "" : "s"}`,
      pageWidth - margin - 4,
      y + 6.5,
      { align: "right" }
    );
    y += 14;

    for (const item of group.items) {
      const quantity = `${item.quantity}${item.unit ? ` ${item.unit}` : ""}`;
      const nameLines = document.splitTextToSize(item.name, contentWidth - 55) as string[];
      const rowHeight = Math.max(9, nameLines.length * 4.5 + 3);
      addPageIfNeeded(rowHeight);
      document.setTextColor(item.checked ? 120 : 34, item.checked ? 120 : 34, item.checked ? 120 : 34);
      document.setFont("helvetica", item.checked ? "normal" : "bold");
      document.setFontSize(9.5);
      document.text(item.checked ? "[x]" : "[ ]", margin + 2, y + 4);
      document.text(nameLines, margin + 12, y + 4);
      document.setFont("helvetica", "normal");
      document.text(quantity, pageWidth - margin - 2, y + 4, { align: "right" });
      y += rowHeight;
      document.setDrawColor(225, 225, 225);
      document.line(margin, y - 1.5, pageWidth - margin, y - 1.5);
    }
    y += 4;
  }

  addPageIfNeeded(12);
  document.setTextColor(110, 110, 110);
  document.setFont("helvetica", "normal");
  document.setFontSize(8);
  document.text("Generated by AI Chef - Happy cooking!", pageWidth / 2, y + 3, { align: "center" });
  document.save(`ai-chef-shopping-list-${new Date().toISOString().slice(0, 10)}.pdf`);
}
